export const UserData = [
  {
    end_year: "",
    intensity: 6,
    sector: "Energy",
    topic: "gas",
    insight: "Annual Energy Outlook",
    url: "http://www.eia.gov/outlooks/aeo/pdf/0383(2017).pdf",
    region: "Northern America",
    start_year: "",
    impact: "",
    added: "January, 20 2017 03:51:25",
    published: "January, 09 2017 00:00:00",
    country: "United States of America",
    relevance: 2,
    pestle: "Industries",
    source: "EIA",
    title:
      "U.S. natural gas consumption is expected to increase during much of the projection period.",
    likelihood: 3,
  },
  {
    end_year: "",
    intensity: 6,
    sector: "Energy",
    topic: "oil",
    insight: "Annual Energy Outlook",
    url: "http://www.eia.gov/outlooks/aeo/pdf/0383(2017).pdf",
    region: "Northern America",
    start_year: "",
    impact: "",
    added: "January, 20 2017 03:51:24",
    published: "January, 09 2017 00:00:00",
    country: "United States of America",
    relevance: 2,
    pestle: "Industries",
    source: "EIA",
    title:
      "Reference case U.S. crude oil production is projected to recover from recent declines.",
    likelihood: 3,
  },
  {
    end_year: "",
    intensity: 6,
    sector: "Energy",
    topic: "consumption",
    insight: "Annual Energy Outlook",
    url: "http://www.eia.gov/outlooks/aeo/pdf/0383(2017).pdf",
    region: "Northern America",
    start_year: "",
    impact: "",
    added: "January, 20 2017 03:51:23",
    published: "January, 09 2017 00:00:00",
    country: "United States of America",
    relevance: 2,
    pestle: "Industries",
    source: "EIA",
    title:
      "U.S. petroleum consumption is projected to remain below the 2005 level.",
    likelihood: 3,
  },
  {
    end_year: "",
    intensity: 6,
    sector: "",
    topic: "market",
    insight: "N-Hexane Market Hit at a CAGR of 5% by 2024 - PMR Report",
    url: "http://www.sbwire.com/press-releases/n-hexane-market-hit-at-a-cagr-of-5-by-2024-pmr-report-761520.htm",
    region: "World",
    start_year: "",
    impact: "",
    added: "January, 19 2017 00:55:54",
    published: "January, 18 2017 00:00:00",
    country: "",
    relevance: 2,
    pestle: "Economic",
    source: "SBWire",
    title:
      "Polymerization will remain top 3 end-users in global n-Hexane Market.",
    likelihood: 3,
  },
  {
    end_year: "",
    intensity: 6,
    sector: "Energy",
    topic: "oil",
    insight: "N-Hexane Market Hit at a CAGR of 5% by 2024 - PMR Report",
    url: "http://www.sbwire.com/press-releases/n-hexane-market-hit-at-a-cagr-of-5-by-2024-pmr-report-761520.htm",
    region: "World",
    start_year: "",
    impact: "",
    added: "January, 19 2017 00:55:52",
    published: "January, 18 2017 00:00:00",
    country: "",
    relevance: 2,
    pestle: "Economic",
    source: "SBWire",
    title:
      "High demand for n-Hexane in oil extraction owing to its effectiveness and high yield is expected to propel the global n-Hexane Market.",
    likelihood: 3,
  },
  {
    end_year: 2018,
    intensity: 16,
    sector: "Energy",
    topic: "oil",
    insight: "Oil prices will be much more volatile in 2017",
    url: "http://www.news.tracanada.ca/2017/01/16/oil-prices-will-be-much-more-volatile-in-2017/",
    region: "World",
    start_year: 2017,
    impact: "",
    added: "January, 17 2017 04:19:59",
    published: "January, 16 2017 00:00:00",
    country: "",
    relevance: 4,
    pestle: "Economic",
    source: "TRAC News",
    title:
      "Global oil prices will witness much more volatility in 2017 even though markets may rebalance in the first half of the year if output cuts pledged by producers are implemented.",
    likelihood: 4,
  },
  {
    end_year: 2018,
    intensity: 16,
    sector: "",
    topic: "gdp",
    insight:
      "IMF affirms Nigeria's recovery from recession, with 0.8% growth forecast",
    url: "http://www.vanguardngr.com/2017/01/imf-affirms-nigerias-recovery-recession-0-8-growth-forecast/",
    region: "Western Africa",
    start_year: 2017,
    impact: "",
    added: "January, 17 2017 03:25:45",
    published: "January, 16 2017 00:00:00",
    country: "Nigeria",
    relevance: 4,
    pestle: "Economic",
    source: "Vanguard News",
    title:
      "Nigeria Gross Domestic Product will grow by 0.8 percent in 2017 and 2.3 percent in 2018.",
    likelihood: 4,
  },
  {
    end_year: "",
    intensity: 4,
    sector: "Manufacturing",
    topic: "production",
    insight: "The Slow Road Back: Oil & Gas Industry Outlook for 2017",
    url: "http://deloitte.wsj.com/riskandcompliance/2017/01/10/the-slow-road-back-oil-gas-industry-outlook-for-2017/",
    region: "Northern America",
    start_year: "",
    impact: "",
    added: "January, 17 2017 02:21:11",
    published: "",
    country: "United States of America",
    relevance: 2,
    pestle: "Industries",
    source: "WSJ",
    title:
      "U.S. production could begin to ramp back up following the rig count upturn.",
    likelihood: 2,
  },
];
